# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flightassist 
spec:
  rules:
  - host: lincluster.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /
        backend:
          serviceName: flightassist-service 
          servicePort: 3000 
